[package]
name = "ruuvi-sensor-protocol"
version = "0.3.0"
authors = ["Atte Lautanala <atte.lautanala@gmail.com>"]
edition = "2018"
description = "Ruuvi sensor protocol parser implementation"
repository = "https://github.com/lautat/ruuvi-sensor-protocol-rs"
readme = "README.md"
keywords = ["ruuvi", "ruuvitag"]
categories = ["parser-implementations"]
license = "MIT"

[dependencies]
